# Generated by Django 3.1.2 on 2020-11-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201027_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='main.worker'),
        ),
    ]
