# Generated by Django 3.1.2 on 2020-11-08 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201108_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enters', to='main.worker'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='main.worker'),
        ),
        migrations.AlterField(
            model_name='gap',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='media/documents/'),
        ),
        migrations.AlterField(
            model_name='gap',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='main.worker'),
        ),
        migrations.AlterField(
            model_name='lateness',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latenesses', to='main.worker'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
