# Generated by Django 3.1.2 on 2020-12-09 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201208_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='end_day',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='start_day',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
