# Generated by Django 3.1.2 on 2020-12-13 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201209_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exit',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
