# Generated by Django 3.1.2 on 2020-12-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201215_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='gap',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/'),
        ),
    ]
