# Generated by Django 3.1.2 on 2020-12-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201215_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='gap',
            name='document',
            field=models.FileField(upload_to='media/documents/', null=True, blank=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='worker',
            name='avatar',
        ),
    ]
