# Generated by Django 3.1.2 on 2020-12-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201219_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gap',
            name='reason',
            field=models.IntegerField(choices=[(1, 'Выходной'), (2, 'Больничный'), (3, 'Отпуск'), (4, 'Командировка')], null=True),
        ),
    ]
